COLOR_SCHEMES: dict[str, dict[str, str]] = {
    "clean": {
        "--bg": "#ffffff",
        "--fg": "#222222",
        "--accent": "#0055cc",
        "--link": "#0055cc",
        "--link-visited": "#551a8b",
        "--border": "#dddddd",
        "--heading": "#222222",
        "--code-bg": "#f5f5f5",
        "--code-fg": "#333333",
    },
    "neon": {
        "--bg": "#1a1a2e",
        "--fg": "#ffcc00",
        "--accent": "#ff6600",
        "--link": "#ff6600",
        "--link-visited": "#ff6600",
        "--border": "#333366",
        "--heading": "#ffcc00",
        "--code-bg": "#111111",
        "--code-fg": "#00ff00",
        "--marquee-bg": "navy",
        "--counter-bg": "#111111",
        "--counter-fg": "#00ff00",
    },
    "midnight": {
        "--bg": "#000040",
        "--fg": "#e0e0e0",
        "--accent": "#ffff99",
        "--link": "#6699ff",
        "--link-visited": "#9966cc",
        "--border": "#444466",
        "--heading": "#ffff99",
        "--code-bg": "#000030",
        "--code-fg": "#e0e0e0",
        "--footer-fg": "#888888",
    },
    "terminal": {
        "--bg": "#000000",
        "--fg": "#00ff00",
        "--accent": "#00ff00",
        "--link": "#00ffff",
        "--link-visited": "#00ffff",
        "--border": "#003300",
        "--heading": "#00ff00",
        "--code-bg": "#001100",
        "--code-fg": "#00ff00",
        "--footer-fg": "#006600",
    },
    "starfield": {
        "--bg": "#000022",
        "--fg": "#aaccff",
        "--accent": "#ffcc00",
        "--link": "#66aaff",
        "--link-visited": "#8888cc",
        "--border": "#333366",
        "--heading": "#ffcc00",
        "--code-bg": "#000030",
        "--code-fg": "#aaccff",
        "--panel-bg": "rgba(0,0,30,0.7)",
        "--footer-fg": "#667799",
        "--badge-bg": "#222222",
        "--badge-fg": "#aaaaaa",
    },
    "parchment": {
        "--bg": "#e8e8e0",
        "--fg": "#333333",
        "--accent": "#cc9900",
        "--link": "#0000cc",
        "--link-visited": "#660099",
        "--border": "#cccccc",
        "--heading": "#333333",
        "--code-bg": "#d8d8d0",
        "--code-fg": "#333333",
        "--nav-bg": "#d0d0d0",
        "--construction-bg": "#ffffee",
        "--construction-border": "#cc9900",
        "--construction-fg": "#663300",
    },
    # ------------------------------------------------------------------
    # "papered" family — 10 schemes paired one-to-one with the papered
    # themes (folio, alpine, harbor, …, nocturne). All carry the same
    # custom-property contract so the shared _papered/_base.html can
    # consume them uniformly: --card-bg, --ink-light, --pattern-fg, and
    # --pattern-accent on top of the standard set.
    # ------------------------------------------------------------------
    "folio": {
        "--bg": "#f1e8d4",
        "--fg": "#2a2418",
        "--heading": "#2a2418",
        "--accent": "#a8742a",
        "--link": "#5a4a1a",
        "--link-visited": "#6e3a1a",
        "--border": "#c8b89a",
        "--rule": "#c8b89a",
        "--code-bg": "#e8dec8",
        "--code-fg": "#3a2f1f",
        "--card-bg": "rgba(252, 247, 235, 0.96)",
        "--ink-light": "#6e6347",
        "--pattern-fg": "#8a7a55",
        "--pattern-accent": "#a8742a",
    },
    "alpine": {
        "--bg": "#ecf0f4",
        "--fg": "#1f2937",
        "--heading": "#0f172a",
        "--accent": "#2563eb",
        "--link": "#1e40af",
        "--link-visited": "#5b21b6",
        "--border": "#cbd5e1",
        "--rule": "#cbd5e1",
        "--code-bg": "#e2e8f0",
        "--code-fg": "#1f2937",
        "--card-bg": "rgba(255, 255, 255, 0.94)",
        "--ink-light": "#4b5563",
        "--pattern-fg": "#94a3b8",
        "--pattern-accent": "#2563eb",
    },
    "harbor": {
        "--bg": "#e8dfc7",
        "--fg": "#142c47",
        "--heading": "#0e2238",
        "--accent": "#b8513a",
        "--link": "#142c47",
        "--link-visited": "#4e2e6e",
        "--border": "#b8a886",
        "--rule": "#b8a886",
        "--code-bg": "#d8cdb0",
        "--code-fg": "#142c47",
        "--card-bg": "rgba(244, 235, 215, 0.93)",
        "--ink-light": "#4a5e7a",
        "--pattern-fg": "#6e8094",
        "--pattern-accent": "#b8513a",
    },
    "engineroom": {
        "--bg": "#f5f1e8",
        "--fg": "#161616",
        "--heading": "#000000",
        "--accent": "#b91c1c",
        "--link": "#1d4ed8",
        "--link-visited": "#6d28d9",
        "--border": "#c5beae",
        "--rule": "#c5beae",
        "--code-bg": "#e8e2d2",
        "--code-fg": "#161616",
        "--card-bg": "rgba(252, 248, 238, 0.95)",
        "--ink-light": "#555555",
        "--pattern-fg": "#8a8270",
        "--pattern-accent": "#b91c1c",
    },
    "kiln": {
        "--bg": "#e9d8c0",
        "--fg": "#3a2515",
        "--heading": "#2a1810",
        "--accent": "#d04e1f",
        "--link": "#8a3010",
        "--link-visited": "#5a2a4a",
        "--border": "#c4a884",
        "--rule": "#c4a884",
        "--code-bg": "#d8c4a8",
        "--code-fg": "#3a2515",
        "--card-bg": "rgba(247, 235, 218, 0.94)",
        "--ink-light": "#6a4f3a",
        "--pattern-fg": "#8a6a4a",
        "--pattern-accent": "#d04e1f",
    },
    "latticework": {
        "--bg": "#f0ece0",
        "--fg": "#1a1a1a",
        "--heading": "#000000",
        "--accent": "#0d7377",
        "--link": "#0d7377",
        "--link-visited": "#6d28d9",
        "--border": "#b8b2a0",
        "--rule": "#b8b2a0",
        "--code-bg": "#e2dec8",
        "--code-fg": "#1a1a1a",
        "--card-bg": "rgba(248, 245, 232, 0.94)",
        "--ink-light": "#4a4a4a",
        "--pattern-fg": "#7a7560",
        "--pattern-accent": "#0d7377",
    },
    "meadow": {
        "--bg": "#e8eedc",
        "--fg": "#1f2e1a",
        "--heading": "#0f1f0a",
        "--accent": "#5b8240",
        "--link": "#2c5a18",
        "--link-visited": "#5e3e7a",
        "--border": "#b8c4a0",
        "--rule": "#b8c4a0",
        "--code-bg": "#d4dec0",
        "--code-fg": "#1f2e1a",
        "--card-bg": "rgba(247, 250, 236, 0.92)",
        "--ink-light": "#4a5d3a",
        "--pattern-fg": "#88997a",
        "--pattern-accent": "#5b8240",
    },
    "ember": {
        "--bg": "#1a1814",
        "--fg": "#e8dccc",
        "--heading": "#f5e6d2",
        "--accent": "#d97f4a",
        "--link": "#f5b787",
        "--link-visited": "#d49aa0",
        "--border": "#4a4338",
        "--rule": "#4a4338",
        "--code-bg": "#2a2620",
        "--code-fg": "#e8dccc",
        "--card-bg": "rgba(36, 32, 26, 0.92)",
        "--ink-light": "#a89d8c",
        "--pattern-fg": "#6a5d4d",
        "--pattern-accent": "#d97f4a",
    },
    "quarry": {
        "--bg": "#161614",
        "--fg": "#d8d3c2",
        "--heading": "#efe8d5",
        "--accent": "#c79b3e",
        "--link": "#d4b25e",
        "--link-visited": "#b69af0",
        "--border": "#3e3c33",
        "--rule": "#3e3c33",
        "--code-bg": "#242420",
        "--code-fg": "#d8d3c2",
        "--card-bg": "rgba(28, 28, 24, 0.92)",
        "--ink-light": "#948e7e",
        "--pattern-fg": "#5e5b50",
        "--pattern-accent": "#c79b3e",
    },
    "nocturne": {
        "--bg": "#0e1430",
        "--fg": "#d8dde8",
        "--heading": "#f0f2f8",
        "--accent": "#c5a86d",
        "--link": "#9eb8e8",
        "--link-visited": "#c8a8e8",
        "--border": "#2a3050",
        "--rule": "#2a3050",
        "--code-bg": "#1a2040",
        "--code-fg": "#d8dde8",
        "--card-bg": "rgba(20, 26, 50, 0.92)",
        "--ink-light": "#8a92a8",
        "--pattern-fg": "#4a527a",
        "--pattern-accent": "#c5a86d",
    },
}

DEFAULT_SCHEMES: dict[str, str] = {
    "default": "clean",
    "geocities": "neon",
    "academic": "midnight",
    "hacker": "terminal",
    "angelfire": "starfield",
    "web-ring": "parchment",
    "90s-academic": "parchment",
    # papered family — each theme defaults to its eponymous scheme
    "folio": "folio",
    "alpine": "alpine",
    "harbor": "harbor",
    "engineroom": "engineroom",
    "kiln": "kiln",
    "latticework": "latticework",
    "meadow": "meadow",
    "ember": "ember",
    "quarry": "quarry",
    "nocturne": "nocturne",
}


def available_color_schemes() -> list[str]:
    return list(COLOR_SCHEMES.keys())


def get_color_scheme(name: str) -> dict[str, str]:
    if name not in COLOR_SCHEMES:
        raise ValueError(f"Unknown color scheme: {name}")
    return COLOR_SCHEMES[name]


def color_scheme_css(name: str) -> str:
    props = get_color_scheme(name)
    lines = "; ".join(f"{k}: {v}" for k, v in props.items())
    return f"<style>:root {{ {lines} }}</style>"
